### ISSUE TITLE
allow kubernetes.io/externalIP to be loaded from the ConfigMap too?

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/exposecontroller#3]
I'm experimenting turning exposecontroller into a stand alone YAML that can be run directly on openshift or kubernetes (or helm) then configured later on via a ConfigMap if required. 

I'm just about there but right now the node has to be annotated with "kubernetes.io/externalIP" or the exposecontroller barfs with:

```
2016-09-11 06:47:34.944279 I | Unable to find kubernetes.io/externalIP label, was gofabric8 used to deploy?
```

which is a nice helpful message BTW! I'm wondering if for openshift templates, we could supply this externalIP address as a template parameter so folks can specify it via `oc process` etc?

e.g. so if gofabric8 isn't used and the node doesn't have the annotation, we fall back to looking for a value in the ConfigMap (which we can configure manually via oc or default via an openshift template parameter?)

**Comment by rawlingsj** [comment]
Yeah sounds good - I'll add that in.

**Comment by jimmidyson** [comment]
Do you think we should change the label prefix? kubernetes.io/ should be reserved for kubernetes labels imo, we should probably prefix with fabric8.io instead to make sure we don't conflict in case that label is used in future.

**Comment by rawlingsj** [comment]
yeah we can, it was originally done intentionally whilst waiting for https://github.com/kubernetes/minikube/issues/544#issue-174710407

As it happens it's not going to be done by minikube anymore, but I still think we need the externalIP if we run CDK / oc cluster up / fabric8 vagrant so that we know the external IP address to create a NodePort url.  But agreed, I'll check its still needed and if it is then change it to `fabric8io`

**Comment by jstrachan** [comment]
@rawlingsj woulds good! Being able to configure the externalIP via the ConfigMap sounds good too

**Comment by jstrachan** [comment]
@rawlingsj BTW I've got the changes necesssary to make an OpenShift template + configmap for exposecontroller as part of a new release - will push later...
