### ISSUE TITLE
Annotate ingress?

### ISSUE THREAD

**Issue by tdcox** [jenkins-x/exposecontroller#73]
Just a thought, is it possible to annotate the ingress with something like:

metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "nginx-ingress"

Then when deploying to GKE, you could start by declaring:

gcloud compute addresses create nginx-ingress --global

Which would give you a static IP that could be mapped to an external domain name before installing fabric8 with the declared domain.

The ingress should then pick up the static IP rather than requesting a new one.

**Comment by rawlingsj** [comment]
We could do this and get gofabric8 to call the gcloud command during the deploy, but I'm not yet sure how we'd detect it's GKE we're deploying to rather than AWS or any other kubernetes cluster. 

I wonder if using the current approach of delegating to the cluster specific kube service load balancer to create the static IP needs to be a bit more clever and avoid hanging if quota exceeds or no LB available to create the external IP?

If that's not enough we could add a flag to gofabric8 deploy to say it's GKE and do the gcloud CLI command?

**Comment by tdcox** [comment]
The use case is to create a route using a domain mapped to a predefined IP, so I guess we need a strategy for all common cloud platforms.

Given that it's just an annotation, would it not just be ignored on anything other than GKE?

I'm not clear where you would need to know internally that you were deploying on GKE. Is it not the case that you just request a new IP and GKE makes the association based upon the annotation and issues a predefined value rather than pulling a new one from a pool?
